version: '3.4'

services:
  shopapi:
    image: ${DOCKER_REGISTRY-}shopapi
    build:
      context: .
      dockerfile: ShopApi/Dockerfile
    depends_on:
        - db
   
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "1Secure*Password1#"